### ISSUE TITLE
 version of jupyter does this support?

### ISSUE THREAD

**Issue by dshakey** [manuzhang/jupyterlab_spark#1]
what version of jupyter does this support?

#1 Conflicting Dependencies:
JupyterLab              Extension      Package
>=1.0.0 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/application
See the log file for details:  /tmp/jupyterlab-debug-xs1n9oe4.log

**Comment by manuzhang** [comment]
@dshakey, hi, I just added support for for JupyterLab 1.0. Please try it out. Thanks.
