### ISSUE TITLE
Blank page in jupyterlab

### ISSUE THREAD

**Issue by canhtran** [manuzhang/jupyterlab_spark#6]
Hi @manuzhang ,

Thank you very much for the tool, this is exactly what I'm looking at the moment.
However, after follow your guide, I have the blank page instead of Spark History UI. Do you have any idea about it ?

![image](https://user-images.githubusercontent.com/3214379/85705987-59150480-b714-11ea-8fca-ea544833e9b5.png)

Thanks in advance

**Comment by canhtran** [comment]
For more information, I'm using Jupyterlab 2.1.*

**Comment by manuzhang** [comment]
Can you share the error info from the browser inspect console ?

**Comment by jcatana** [comment]
chromewebdata/:1 Blocked script execution in 'chrome-error://chromewebdata/' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

I see the same issue with jupyterlab 2.1.5

**Comment by manuzhang** [comment]
@canhtran @jcatana,
Could you try the latest 0.3.1 version ?

**Comment by canhtran** [comment]
@manuzhang thanks for the quick fix, it's working now. If it's possible, can I suggest to change the spark url into dynamic one,  `localhost` and `port` may not be fixed for other usecases

**Comment by manuzhang** [comment]
Yes, that's on my todo list. It will be great if you can send a PR.

**Comment by canhtran** [comment]
@manuzhang surely,  let me close this issue. Will send the PR for that
